version: 2

models:
  - name: dim_carmake
    description: "Dimensión de Marcas de Vehículos. Contiene una clave única para cada marca."
    columns:
      - name: ID_CARMAKE
        description: "Clave subrogada única para cada marca de vehículo."
        tests:
          - unique
          - not_null
      - name: CARMAKE
        description: "Nombre de la marca del vehículo."
        tests:
          - not_null

  - name: dim_salesperson
    description: "Dimensión de Vendedores. Contiene una clave única para cada vendedor."
    columns:
      - name: ID_SALESPERSON
        description: "Clave subrogada única para cada vendedor."
        tests:
          - unique
          - not_null
      - name: SALESPERSON
        description: "Nombre del vendedor."

  - name: fact_monthly_sales
    description: "Tabla de hechos de ventas mensuales por vendedor y marca."
    columns:
      - name: DDATE
        description: "Mes de la venta (primer día del mes)."
        tests:
          - not_null
      - name: ID_SALESPERSON
        description: "Clave foránea a la dimensión de vendedores (dim_saleperson)."
        tests:
          - not_null
          - relationships:
              to: ref('dim_saleperson')
              field: ID_SALESPERSON
      - name: ID_CARMAKE
        description: "Clave foránea a la dimensión de marcas (dim_carmake)."
        tests:
          - not_null
          - relationships:
              to: ref('dim_carmake')
              field: ID_CARMAKE
      - name: TOTALSALE
        description: "Monto total de la venta neta para ese mes, vendedor y marca."
      - name: TOTALCOM
        description: "Monto total de la comisión para ese mes, vendedor y marca."
